# Encrypted file for storing sensitive information

# Infrastructure settings
KEYVAULT_NAME: kv-dev
TENANT_ID: 3erewfasr3-3d4d-324rf-43rew-432re432rewr3
STORAGE_ACCOUNT: storage-dev

# App settings
APP_NAME: "dev-webapp"
APP_HOSTNAME: "dev.webapp"
DEPLOYMENT_USER: "dev_deployment_user"
DEPLOYMENT_PASSWORD: "dev_deployment_password"

# DB2 settings
DB2_DRIVER_CLASS_NAME: "com.ibm.db2.jcc.DB2Driver"
DB2_HOSTNAME: "10.0.0.1"
DB2_PORT: 50000
DB2_DEFAULT_DB_NAME: "SAMPLE"
DB2_CLIENT_CERT_NAME: "dev-db2-client-cert"
DB2_CLIENT_CERT_PATH: "/path/to/dev/db2/client/cert/dev-db2-client-cert.pem"
DB2_CLIENT_KEY_NAME: "dev-db2-client-key"
DB2_CLIENT_KEY_PATH: "/path/to/dev/db2/client/key/dev-db2-client-key.pem"
DB2_CA_CERT_NAME: "dev-db2-ca-cert"
DB2_CA_CERT_PATH: "/path/to/dev/db2/ca/cert/dev-db2-ca-cert.pem"

# ORACLE settings
ORACLE_SECRET_NAME: "oracle-dev-secret"
ORACLE_DRIVER_CLASS_NAME: "oracle.jdbc.OracleDriver"
ORACLE_HOSTNAME: "10.0.1.1"
ORACLE_PORT: 1521
ORACLE_SERVICE_NAME: "orclpdb1"
# Can be deleted after initial setup, Creds are pushed to Keyvault
ORACLE_USERNAME: "admin"
ORACLE_PASSWORD: "P#a$s0rD"
